---
kind: pipeline
type: docker
name: Build

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: ruby:3.1-slim-bullseye
    commands:
      - apt update && apt install -y --no-install-recommends build-essential git
      - make install
      - make build

---
kind: pipeline
type: docker
name: Publish

platform:
  os: linux
  arch: amd64

steps:
  - name: Build and publish docker image
    image: plugins/docker
    settings:
      registry: ghcr.io
      repo: ghcr.io/kevinmidboe/schleppe-lab
      dockerfile: Dockerfile
      username:
        from_secret: github_username
      password:
        from_secret: github_password
      tags: latest

trigger:
  event:
    include:
      - push
    exclude:
      - pull_request
  branch:
    - main

depends_on:
  - Build

---
kind: pipeline
type: docker
name: Deploy

platform:
  os: linux
  arch: amd64

steps:
  - name: Prepare kubernetes environment
    image: alpine/k8s:1.25.15
    commands:
      - mkdir -p /root/.kube
      - echo $KUBE_CONFIG | base64 -di > /root/.kube/config
    environment:
      KUBE_CONFIG:
        from_secret: kube_config
    volumes:
    - name: kube-config
      path: /root/.kube

  - name: Deploy to kubernetes
    image: alpine/k8s:1.25.15
    commands:
      - export IMAGE="ghcr.io/kevinmidboe/${DRONE_REPO_NAME}:${DRONE_COMMIT_SHA}"
      - cat .kubernetes/*.yml
        | envsubst
        | kubectl --kubeconfig=/root/.kube/config apply -f -
    volumes:
    - name: kube-config
      path: /root/.kube
    when:
      event:
        include:
          - push
        exclude:
          - pull_request
      branch:
        - main
        - feat/ci-vault-secrets

depends_on:
  - Build
  - Publish

volumes:
- name: kube-config
  temp: {}

---
kind: secret
name: github_username
get:
  path: schleppe/data/drone/${DRONE_REPO_NAME}
  name: GITHUB_USERNAME

---
kind: secret
name: github_password
get:
  path: schleppe/data/drone/${DRONE_REPO_NAME}
  name: GITHUB_PASSWORD

---
kind: secret
name: kube_Config
get:
  path: schleppe/data/drone/${DRONE_REPO_NAME}
  name: KUBE_CONFIG

---
kind: signature
hmac: c3b55ead723a89b3e9c27f81ad324d852f42de036b27ecf8a513f07339198773

...
