---
kind: pipeline
type: docker
name: Build and publish

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: ruby:3.1-slim-bullseye
    commands:
      - apt update && apt install -y --no-install-recommends build-essential git
      - make install
      - make build

  - name: Build and publish docker image
    image: plugins/docker
    settings:
      registry: ghcr.io
      repo: ghcr.io/kevinmidboe/schleppe-lab
      dockerfile: Dockerfile
      username:
        from_secret: GITHUB_USERNAME
      password:
        from_secret: GITHUB_PASSWORD
      tags: latest
    when:
      event:
        include:
          - push
        exclude:
          - pull_request
      branch:
        - main

---
kind: signature
hmac: 46d4d087047afb6e18032e1fea13ba964589d86aaf012343821804612baf5678

...
