---
kind: pipeline
type: docker
name: Build and publish

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: ruby:3.1-slim-bullseye
    commands:
      - apt update && apt install -y --no-install-recommends build-essential git
      - make install
      - make build

  - name: Build and publish docker image
    image: plugins/docker
    settings:
      registry: ghcr.io
      repo: ghcr.io/kevinmidboe/schleppe-lab
      dockerfile: Dockerfile
      username:
        from_secret: github_username
      password:
        from_secret: github_password
      tags: latest
    when:
      event:
        include:
          - push
        exclude:
          - pull_request
      branch:
        - main


---
kind: pipeline
type: docker
name: Deploy

platform:
  os: linux
  arch: amd64

steps:
  - name: Prepare kubernetes environment
    image: alpine/k8s:1.25.15
    commands:
      - mkdir -p /root/.kube
      - echo $KUBE_CONFIG | base64 -di > /root/.kube/config
      - export IMAGE="ghcr.io/kevinmidboe/k9e.no:${DRONE_COMMIT_SHA}"

  - name: Deploy to kubernetes
    image: alpine/k8s:1.25.15
    commands:
      - cat .kubernetes/*.yml
        | envsubst
        | kubectl --kubeconfig=/root/.kube/config apply -f -
    environment:
      KUBE_CONFIG:
        from_secret: KUBE_CONFIG
    when:
      event:
        include:
          - push
        exclude:
          - pull_request
      branch:
        - main
        - feat/ci-vault-secrets

depends_on:
  - Build and publish

---
kind: secret
name: github_username
get:
  path: schleppe/data/drone/${DRONE_REPO_NAME}
  name: GITHUB_USERNAME

---
kind: secret
name: github_password
get:
  path: schleppe/data/drone/${DRONE_REPO_NAME}
  name: GITHUB_PASSWORD

---
kind: signature
hmac: 8183dff7ea6b63de2d75650d40df457f018e295f4805e43e6014827931ebf62f

...
