---
kind: pipeline
type: docker
name: Build and publish

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: ruby:3.1-slim-bullseye
    commands:
      - apt update && apt install -y --no-install-recommends build-essential git
      - gem update --system && gem install jekyll bundler
      - bundle install
      - jekyll build

  - name: Build and publish docker image
    image: plugins/docker
    settings:
      registry: ghcr.io
      repo: ghcr.io/kevinmidboe/schleppe-lab
      dockerfile: Dockerfile
      username:
        from_secret: GITHUB_USERNAME
      password:
        from_secret: GITHUB_PASSWORD
      tags: latest
    when:
      event:
        include:
          - push
        exclude:
          - pull_request
      branch:
        - main

---
kind: signature
hmac: 45250a8e9456b053fcbcf7c95fbb6707233cad782f9188e44518d44b174c2379

...
