---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: schleppe-lab
  name: schleppe-lab-service
  namespace: schleppe-lab
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: schleppe-lab
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
